# Generated by Django 4.2.4 on 2023-08-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='service_img',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='webservices/'),
        ),
    ]
