# Generated by Django 4.2.4 on 2023-08-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_alter_webservice_service_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webservice',
            name='id',
        ),
        migrations.AddField(
            model_name='webservice',
            name='service_id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='S_ID'),
        ),
    ]
